# UM DICC Cluster Environment configurations

input_dir: "input"
artifacts_dir: "artifacts"
dataset_artifacts_dir: "artifacts"
experiment_artifacts_dir: "artifacts"
outputs_dir: "outputs"

store_filter: ""  # Empty means full dataset (30,490 series)

# PyTorch Lightning Trainer device configurations
accelerator: "gpu"
devices: 1
num_workers: 4
precision: 16
gradient_clip_val: 0.1

seed: 42
