# Kaggle Environment configurations

input_dir: "/kaggle/input/competitions/m5-forecasting-accuracy"
artifacts_dir: "artifacts"
outputs_dir: "outputs"

store_filter: ""  # Empty means full dataset (30,490 series)

# PyTorch Lightning Trainer device configurations
accelerator: "gpu"
devices: 1
num_workers: 2
precision: 32

seed: 42
