# Local Environment configurations

input_dir: "input"
artifacts_dir: "artifacts"
dataset_artifacts_dir: "artifacts"
experiment_artifacts_dir: "artifacts"
outputs_dir: "outputs"

store_filter: ""  # "" for all stores

# PyTorch Lightning Trainer device configurations
accelerator: "cpu"
devices: "auto"
num_workers: 0
precision: 32
gradient_clip_val: 0.1

seed: 42
